server:
  port: ${PORT}
  forward-headers-strategy: framework

spring:
  cloud:
    aws:
      cloudwatch:
        enabled: false
        region: ${AWS_REGION:ap-northeast-2}

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    admin:
      auto-create: false # 토픽 자동 생성 차단
    topic:
      partitions: ${KAFKA_TOPIC_PARTITIONS:3}
      replicas: ${KAFKA_TOPIC_REPLICAS:3}
    listener:
      concurrency: 3

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${OAUTH_REDIRECT_URI}/login/oauth2/code/kakao"
          google:
            redirect-uri: "${OAUTH_REDIRECT_URI}/login/oauth2/code/google"

# Common Logging
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

opensearch:
  uris: ${OPENSEARCH_HOST}
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
      group:
        readiness:
          exclude: mail
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  cloudwatch:
    metrics:
      export:
        enabled: false
        namespace: clothesplz
        step: 1m

clothesplz:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
  jwt:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    access-token-exp: ${ACCESS_TOKEN_EXP}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    refresh-token-exp: ${REFRESH_TOKEN_EXP}
  oauth:
    redirect-uri: ${OAUTH_REDIRECT_URI}
